language: java

before_script:
  - |
    set -euo pipefail
    if [[ ! -f cache/bin/nomad ]]; then
      export GOPATH="$PWD/gopath"
      eval "$(curl -sL https://raw.githubusercontent.com/travis-ci/gimme/master/gimme | GIMME_GO_VERSION=1.9.2 bash)"
      export PATH="$PATH:$GOPATH/bin"
      go get -u github.com/hashicorp/nomad
      cd "$GOPATH/src/github.com/hashicorp/nomad"
      make bootstrap generate
      cd -

      mkdir -p cache/bin
      cd cache/bin
      go build -tags nomad_test github.com/hashicorp/nomad
      cd -
    fi
    set +euo pipefail  # restory options to work around https://github.com/travis-ci/travis-ci/issues/5434
  - export PATH="$PWD/cache/bin:$PATH"

cache:
  directories:
    - $HOME/.m2
    - cache
