language: java

before_script:
  - |
    if [[ ! -f cache/nomad ]]; then
      export GOPATH="$PWD/gopath"
      eval "$(curl -sL https://raw.githubusercontent.com/travis-ci/gimme/master/gimme | GIMME_GO_VERSION=1.8.1 bash)"
      go get github.com/hashicorp/nomad
      cd "$GOPATH/src/github.com/hashicorp/nomad"
      make bootstrap generate

      mkdir -p cache
      cd cache
      go build -tags nomad_test github.com/hashicorp/nomad
    fi

cache:
  directories:
    - $HOME/.m2
    - cache
