dist: trusty
sudo: false

language: java

before_script:
  - |
    set -euo pipefail

    scripts/build-nomad.sh

    nomad_path="$(which nomad)"
    real_nomad_path="$(readlink "${nomad_path}")"
    GOPATH_BIN="$(dirname "${real_nomad_path}")"

    set +euo pipefail  # restore options to work around https://github.com/travis-ci/travis-ci/issues/5434

cache:
  directories:
    - $GOPATH_BIN
    - $HOME/.m2
